function graficarRemuestreo( MzRemBen,IntenRemBen,IntenRemCancer,IntenRemControl,MzRemCancer,MzRemControl)

fprintf('========================================================\n')
fprintf('%s                                                    %s\n',20,22)
fprintf('%s             GRAFICAS REMUESTREO                    %s\n',20,22)
fprintf('%s                                                    %s\n',20,22)
fprintf('%s Funcion que grafica los datos luego del remuestreo %s\n',20,22)
fprintf('%s de Benign, Cancer y Control y muestra sus mapas de %s\n',20,22)
fprintf('%s calor respectivamente.                             %s\n',20,22)
fprintf('%s                                                    %s\n',20,22)
fprintf('========================================================\n')


% Funcion que grafica los datos luego del remuestreo de Benign, Cancer y
% Control y muestra sus mapas de calor respectivamente.
% -----------------------------------------------------------------------
%SINTAXIS: function
%graficar_remuestreo(MzRemBen,IntenRemBen,IntenRemCancer,
%IntenRemControl,MzRemCancer,MzRemControl)
%PARAMETROS:
% MzRemBen = Vector Masas Benign remuestreadas a 10000 puntos.
% IntenRemBen = Matriz intensidades Benign remuestreadas a 10000 puntos.
% MzRemCancer = Vector Masas de Cancer remuestreadas a 10000 puntos.
% IntenRemCancer=Matriz intensidades de Cancer remuestreadas a 10000 puntos. 
% MzRemControl = Vector Masas de Control remuestreadas a 10000 puntos.
% IntenRemControl=Matriz intensidades de Control remuestreadas a 10000 
% puntos.
% Graficas expresadas (Masa/Carga) M/Z vs Intensidades.
%
subplot (3,1,1)
plot(MzRemBen,mean(IntenRemBen'),'b-',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0,0,0])
set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
  'LineWidth'   , 1         );
title('\bfMuestras Ovarian Data WCX2 CSV-Benign RE-muestreadas a 10000',...
    'FontName','Arial','FontSize', 10)
xlabel('Masa/Carga (M/Z)','FontName','Arial','FontSize',8)
ylabel('Intensidad','FontName','Arial','FontSize', 8)
set(gca,'YTick',0:max(mean(IntenRemBen))/5:max(mean(IntenRemBen)), ...
    'fontsize', 8);
set(gca,'XTick',0:max((MzRemBen))/11:max((MzRemBen)),'fontsize', 8);
tick2text(gca, 'yformat', '%.2f');
%tick2text(gca, 'xformat', '%.2f');
axis([min((MzRemBen)), max((MzRemBen)), 0, max(mean(IntenRemBen))])
grid on

subplot (3,1,2)
plot(MzRemCancer,mean(IntenRemCancer'),'r-',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0,0,0])
set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
  'LineWidth'   , 1         );
title('\bfMuestras Ovarian Data WCX2 CSVC-Cancer RE-muestreadas a 10000',...
    'FontName','Arial','FontSize', 10)
xlabel('Masa/Carga (M/Z)','FontName','Arial','FontSize', 8)
ylabel('Intensidad','FontName','Arial','FontSize', 8)

set(gca,'YTick',0:max(mean(IntenRemCancer))/5:max(mean(IntenRemCancer)), ...
    'fontsize', 8);
set(gca,'XTick',0:max((MzRemCancer))/11:max((MzRemCancer)),'fontsize', 8);
tick2text(gca, 'yformat', '%.2f');
%tick2text(gca, 'xformat', '%.2f');
axis([min((MzRemCancer)),max((MzRemCancer)), 0, max(mean(IntenRemCancer))])
grid on

subplot (3,1,3)
plot(MzRemControl,mean(IntenRemControl'),'m-',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0,0,0])
set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
  'LineWidth'   , 1         );
title('\bfMuestras Ovarian Data WCX2 CSV-Control RE-muestreadas a 10000',...
    'FontName','Arial','FontSize', 10)
xlabel('Masa/Carga (M/Z)','FontName','Arial','FontSize', 8)
ylabel('Intensidades','FontName','Arial','FontSize', 8)

set(gca,'YTick',0:max(mean(IntenRemControl))/5:max(mean(IntenRemControl)), ...
    'fontsize', 8);
set(gca,'XTick',0:max((MzRemControl))/11:max((MzRemControl)),'fontsize',8);
tick2text(gca, 'yformat', '%.2f');

axis([min(MzRemControl),max((MzRemControl)),0, max(mean(IntenRemControl))])
grid on
set(gcf, 'Units','centimeters', 'Position',[6 6 12 12]);
saveas(gca, 'myplot.eps','epsc');

% Mapas de calor Benign,Cancer y Control
msheatmap(MzRemBen,IntenRemBen)
% title('\bfMUESTRAS DE DATOS BENIGN','FontName','Arial','FontSize', 12)
xlabel('Masa / Carga M/Z','FontName','Arial','FontSize', 12)
ylabel('Numero De Mediciones','FontName','Arial','FontSize', 12)
set(gca, 'fontsize', 10) 

msheatmap(MzRemCancer,IntenRemCancer)
% title('\bfMUESTRAS DE DATOS CON CANCER','FontName','Arial','FontSize',12)
xlabel('Masa/Carga (M/Z)','FontName','Arial','FontSize', 12)
ylabel('Numero De Mediciones','FontName','Arial','FontSize', 12)
set(gca, 'fontsize', 10)

msheatmap(MzRemControl,IntenRemControl)
% title('\bfMUESTRAS DE DATOS DE CONTROL','FontName','Arial','FontSize',12)
xlabel('Masa / Carga M/Z','FontName','Arial','FontSize', 12)
ylabel('Numero De Mediciones','FontName','Arial','FontSize', 12)
set(gca, 'fontsize', 10)

end
